channels:
- conda-forge
dependencies:
- python=3.12.8
- pip
- pip:
  - mlflow==3.1.0
  - cloudpickle==3.1.1
  - matplotlib==3.10.3
  - numpy==2.3.1
  - pandas==2.3.0
  - rich==14.0.0
  - scipy==1.16.0
  - torch==2.7.1
  - torchgeo==0.7.1
name: mlflow-env
